jobs:
  build: # 2 espaços (Primeiro Job)
    runs-on: ubuntu-latest
    steps:
      # ... (Outros passos do build) ...

      - name: Upload artifact # 6 espaços
        uses: actions/upload-pages-artifact@v3 # 8 espaços
        with: # 8 espaços (CORRETO)
          path: ./dist # 10 espaços

  deploy: # 2 espaços (Segundo Job, ALINHADO com 'build:')
    environment: # 4 espaços
      name: github-pages # 6 espaços
      url: ${{ steps.deployment.outputs.page_url }} # 6 espaços
    needs: build # 4 espaços
    runs-on: ubuntu-latest # 4 espaços
    steps: # 4 espaços
      - name: Deploy to GitHub Pages # 6 espaços
        id: deployment # 8 espaços
        uses: actions/deploy-pages@v4 # 8 espaços
